/*

 FOODTXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __foodtxt_h_INCLUDE
#define __foodtxt_h_INCLUDE

#define foodtxtWidth 18
#define foodtxtHeight 4
#define foodtxtBank 0

extern const unsigned char foodtxt[];

#endif

/* End of FOODTXT.H */
