/*

 HEALERTXTA1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __healertxtA1_h_INCLUDE
#define __healertxtA1_h_INCLUDE

#define healertxtA1Width 18
#define healertxtA1Height 4
#define healertxtA1Bank 0

extern const unsigned char healertxtA1[];

#endif

/* End of HEALERTXTA1.H */
