/*

 SHOPWHETSTONETXTA1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __shopwhetstonetxtA1_h_INCLUDE
#define __shopwhetstonetxtA1_h_INCLUDE

#define shopwhetstonetxtA1Width 18
#define shopwhetstonetxtA1Height 4
#define shopwhetstonetxtA1Bank 0

extern const unsigned char shopwhetstonetxtA1[];

#endif

/* End of SHOPWHETSTONETXTA1.H */
