/*

 DEVLEVEL.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __devlevel_h_INCLUDE
#define __devlevel_h_INCLUDE

#define devlevelWidth 18
#define devlevelHeight 14
#define devlevelBank 0

extern const unsigned char devlevel[];

#endif

/* End of DEVLEVEL.H */
