/*

 LVL004.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __lvl004_h_INCLUDE
#define __lvl004_h_INCLUDE

#define lvl004Width 18
#define lvl004Height 14
#define lvl004Bank 0

extern const unsigned char lvl004[];

#endif

/* End of LVL004.H */
