/*

 LVL010.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __lvl010_h_INCLUDE
#define __lvl010_h_INCLUDE

#define lvl010Width 18
#define lvl010Height 14
#define lvl010Bank 0

extern const unsigned char lvl010[];

#endif

/* End of LVL010.H */
