/*

 LVL0A.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __lvl0a_h_INCLUDE
#define __lvl0a_h_INCLUDE

#define lvl0aWidth 18
#define lvl0aHeight 14
#define lvl0aBank 0

extern const unsigned char lvl0a[];

#endif

/* End of LVL0A.H */
/*

 LVL0B.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __lvl0b_h_INCLUDE
#define __lvl0b_h_INCLUDE

#define lvl0bWidth 18
#define lvl0bHeight 14
#define lvl0bBank 0

extern const unsigned char lvl0b[];

#endif

/* End of LVL0B.H */
/*

 LVL0C.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __lvl0c_h_INCLUDE
#define __lvl0c_h_INCLUDE

#define lvl0cWidth 18
#define lvl0cHeight 14
#define lvl0cBank 0

extern const unsigned char lvl0c[];

#endif

/* End of LVL0C.H */
/*

 LVL0D.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 14
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __lvl0d_h_INCLUDE
#define __lvl0d_h_INCLUDE

#define lvl0dWidth 18
#define lvl0dHeight 14
#define lvl0dBank 0

extern const unsigned char lvl0d[];

#endif

/* End of LVL0D.H */
