/*

 COURSE-CLEAN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 16 x 10
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\all.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __course_clean_h_INCLUDE
#define __course_clean_h_INCLUDE

#define coursecleanWidth 16
#define coursecleanHeight 10
#define coursecleanBank 0

extern const unsigned char courseclean[];

#endif

/* End of COURSE-CLEAN.H */
