/*

 FRAME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\all.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __frame_h_INCLUDE
#define __frame_h_INCLUDE

#define frameWidth 20
#define frameHeight 18
#define frameBank 0

extern const unsigned char frame[];

#endif

/* End of FRAME.H */
