/*

 TEXTFRAME.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 6
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __textframe_h_INCLUDE
#define __textframe_h_INCLUDE

#define textframeWidth 20
#define textframeHeight 6
#define textframeBank 0

extern const unsigned char textframe[];

#endif

/* End of TEXTFRAME.H */
