/*

 TINYHUD.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 3
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\maintiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __tinyhud_h_INCLUDE
#define __tinyhud_h_INCLUDE

#define tinyhudWidth 18
#define tinyhudHeight 3
#define tinyhudBank 0

extern const unsigned char tinyhud[];

#endif

/* End of TINYHUD.H */
