/*

 SHIELDPUBTXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 4
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\font.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __shieldpubtxt_h_INCLUDE
#define __shieldpubtxt_h_INCLUDE

#define shieldpubtxtWidth 18
#define shieldpubtxtHeight 4
#define shieldpubtxtBank 0

extern const unsigned char shieldpubtxt[];

#endif

/* End of SHIELDPUBTXT.H */
