/*

 FONT-81-127.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 81 to 127

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __font_81_127_h_INCLUDE
#define __font_81_127_h_INCLUDE

/* Bank of tiles. */
#define fontBank 0
/* Start of tile array. */
extern const unsigned char font[];

#endif

/* End of FONT-81-127.H */
