/*

 MINE-ENTRANCETXT.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\all.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __mine_entrancetxt_h_INCLUDE
#define __mine_entrancetxt_h_INCLUDE

#define mineentrancetxtWidth 18
#define mineentrancetxtHeight 1
#define mineentrancetxtBank 0

extern const unsigned char mineentrancetxt[];

#endif

/* End of MINE-ENTRANCETXT.H */
