/*

 MINE-ENTRANCETXT.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : Z:\home\magister\repos\graeber2\gbtd\all.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mineentrancetxtWidth 18
#define mineentrancetxtHeight 1
#define mineentrancetxtBank 0

const unsigned char mineentrancetxt[] =
{
  0x23,0x23,0x72,0x76,0x71,0x7A,0x23,0x7A,0x71,0x6B,
  0x6D,0x7E,0x71,0x7C,0x7A,0x23,0x23,0x23
};

/* End of MINE-ENTRANCETXT.C */
